platform :ios, '13.0'

target 'CoordinationControlWorkApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoordinationControlWorkApp
  pod 'SnapKit', '~> 5.0.0'

end
